### ISSUE TITLE
Piano Tuner

### ISSUE THREAD

**Issue by brianamarie** [brianamarie/Wedding#11]
### Piano Tuning

Robert Stout will start tuning at 4, either outside, or inside with rain.

Contact info:
- Bob Stout
- 816 833 1556

#### To-Do:
- [x] Call Bob Stout
- [x] Find Alternative Tuner
- [x] Email Californos about other tuners
- [x] Schedule a tuning
- [x] Agree on pricing
- [x] Pay, with check made out to Robert Stout for $80

**Comment by C-Williams** [comment]
I have no idea if this is where I make note of what I've done, but here's to hoping...

I called Widgans, he is out of town so he can't. I already emailed Californos back, and if we don't here from them today, I will reach out to UMKC and see who they use.

**Comment by brianamarie** [comment]
Fantastic, thank you @C-Williams! ❤️

**Comment by C-Williams** [comment]
Got new contact info for a different tuner. I can call today after Therapy.

**Comment by C-Williams** [comment]
@brianamarie 

Piano tuner all set up!

**Comment by brianamarie** [comment]
@c-williams
 ![best](https://media.giphy.com/media/xT8qB3gj6AxN7AsIta/giphy.gif)
